### ISSUE TITLE
Issue whe the docker use

### ISSUE THREAD

**Issue by EMeric1992** [imTHAI/docker-qbittorrent-filebot#6]
Good morning,

I successfully installed the qbitorrent-FileBot docker and am able to automatically run FileBot after downloading a file from qbitorrent.

In principle, it works, but the problem is that very frequently, the docker does not work correctly and causes a significant slowdown of my Nas.

There is a significant stability problem.

However, when I run qBittorrent in the official [Linuxserver.io](http://linuxserver.io/) docker it works without any slowdown and it does not crash my Nas.

Do you have any advice to resolve my problem?

Thanks in advance.

**Comment by imTHAI** [comment]
Hello,

So it looks like the problem concerns Filebot. Because the qbt I use is the version from linuxserver. 
Is there anything in the logs ? Maybe the nas slows down and/or crashes when filebot copies or moves the media files to your media library ? Are both sources and destinations on the same array/pool ? (I download on a 2to nvme ssd, used as a cache, then the files are copied to my big array where is my media library). 

What filebot actions did you set ? Try to change this setting.

**Comment by EMeric1992** [comment]
Hello and thank you very much for your help!

Indeed I also think that the problem came from filebot.

The slowdown occurred even before the files were moved as soon as the download to qbitorrent was started.


I uninstalled and reinstalled the container several times and for some unknown reason it now works without slowdowns!

The only setting I changed is that I set docker to privilege mode.

I don't know if this is why the problem is solved.


I will let you know if the problem arises again.


THANKS,

Emeric.
